ADSL = "SUBJECT LEVEL ANALYSIS DATASET"
BDS = "BASIC DATA STRUCTURE"
OCCDS = "OCCURRENCE DATA STRUCTURE"
ADDL = "DEVICE LEVEL ANALYSIS DATASET"
MDBDS = "MEDICAL DEVICE BASIC DATA STRUCTURE"
MDOCCDS = "MEDICAL DEVICE OCCURRENCE DATA STRUCTURE"
OTHER = "ADAM OTHER"

ADAM_DATA_STRUCTURE_ALIASES = {
    "ADSL": ADSL,
    "BDS": BDS,
    "OCCDS": OCCDS,
    "ADDL": ADDL,
    "MDBDS": MDBDS,
    "MDOCCDS": MDOCCDS,
}

BDS_INDICATORS = {"PARAMCD", "PARAM", "AVAL", "AVALC"}
MDBDS_INDICATORS = BDS_INDICATORS.copy()
OCCDS_SUFFIXES = {"TERM", "TRT"}
MDOCCDS_SUFFIXES = OCCDS_SUFFIXES.copy()
