ADSL = "SUBJECT LEVEL ANALYSIS DATASET"
BDS = "BASIC DATA STRUCTURE"
OCCDS = "OCCURRENCE DATA STRUCTURE"
OTHER = "ADAM OTHER"

ADAM_DATA_STRUCTURE_ALIASES = {
    "ADSL": ADSL,
    "BDS": BDS,
    "OCCDS": OCCDS,
}

BDS_INDICATORS = {"PARAMCD", "PARAM", "AVAL", "AVALC"}
OCCDS_SUFFIXES = {"TERM", "TRT"}
